#include "OpcodeTables.h"
#include <stdexcept> // For potential error throwing if needed
#include "logger.h"   // For logging errors

namespace GB {

// Constructor: Initializes opcode tables with hardcoded data
// Initialize const member 'unknownOpcodeInfo' in the initializer list
OpcodeTables::OpcodeTables() :
    unknownOpcodeInfo({"UNKNOWN", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x00, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false})
{
    // Now initialize the arrays using the already initialized const member
    standardOpcodes.fill(unknownOpcodeInfo);
    cbPrefixedOpcodes.fill(unknownOpcodeInfo);

    // --- Unprefixed Opcodes ---
    // (Ensure all 256 entries are filled here from the previous hardcoded version)
    standardOpcodes[0x00] = {"NOP", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x00, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x01] = {"LD", 3, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x01, InstructionGroup::X16_LSM, Register::BC, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n16
    standardOpcodes[0x02] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x02, InstructionGroup::X8_LSM, Register::MEM_BC, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x03] = {"INC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x03, InstructionGroup::X16_ALU, Register::BC, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x04] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x04, InstructionGroup::X8_ALU, Register::B, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x05] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x05, InstructionGroup::X8_ALU, Register::B, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x06] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x06, InstructionGroup::X8_LSM, Register::B, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x07] = {"RLCA", 1, {4}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x07, InstructionGroup::X8_RSB, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x08] = {"LD", 3, {20}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x08, InstructionGroup::X16_LSM, Register::MEM_A16, Register::SP, ConditionType::NONE, 0, false};
    standardOpcodes[0x09] = {"ADD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x09, InstructionGroup::X16_ALU, Register::HL, Register::BC, ConditionType::NONE, 0, false};
    standardOpcodes[0x0A] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x0A, InstructionGroup::X8_LSM, Register::A, Register::MEM_BC, ConditionType::NONE, 0, false};
    standardOpcodes[0x0B] = {"DEC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x0B, InstructionGroup::X16_ALU, Register::BC, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x0C] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x0C, InstructionGroup::X8_ALU, Register::C, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x0D] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x0D, InstructionGroup::X8_ALU, Register::C, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x0E] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x0E, InstructionGroup::X8_LSM, Register::C, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x0F] = {"RRCA", 1, {4}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0F, InstructionGroup::X8_RSB, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x10] = {"STOP", 2, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x10, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false}; // operand is n8 (0)
    standardOpcodes[0x11] = {"LD", 3, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x11, InstructionGroup::X16_LSM, Register::DE, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n16
    standardOpcodes[0x12] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x12, InstructionGroup::X8_LSM, Register::MEM_DE, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x13] = {"INC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x13, InstructionGroup::X16_ALU, Register::DE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x14] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x14, InstructionGroup::X8_ALU, Register::D, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x15] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x15, InstructionGroup::X8_ALU, Register::D, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x16] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x16, InstructionGroup::X8_LSM, Register::D, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x17] = {"RLA", 1, {4}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x17, InstructionGroup::X8_RSB, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x18] = {"JR", 2, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x18, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0, false}; // operand is e8
    standardOpcodes[0x19] = {"ADD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x19, InstructionGroup::X16_ALU, Register::HL, Register::DE, ConditionType::NONE, 0, false};
    standardOpcodes[0x1A] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x1A, InstructionGroup::X8_LSM, Register::A, Register::MEM_DE, ConditionType::NONE, 0, false};
    standardOpcodes[0x1B] = {"DEC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x1B, InstructionGroup::X16_ALU, Register::DE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x1C] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x1C, InstructionGroup::X8_ALU, Register::E, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x1D] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x1D, InstructionGroup::X8_ALU, Register::E, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x1E] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x1E, InstructionGroup::X8_LSM, Register::E, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x1F] = {"RRA", 1, {4}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1F, InstructionGroup::X8_RSB, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x20] = {"JR", 2, {12, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x20, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NZ, 0, false}; // op1 is e8
    standardOpcodes[0x21] = {"LD", 3, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x21, InstructionGroup::X16_LSM, Register::HL, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n16
    standardOpcodes[0x22] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x22, InstructionGroup::X8_LSM, Register::MEM_HLI, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x23] = {"INC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x23, InstructionGroup::X16_ALU, Register::HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x24] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x24, InstructionGroup::X8_ALU, Register::H, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x25] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x25, InstructionGroup::X8_ALU, Register::H, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x26] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x26, InstructionGroup::X8_LSM, Register::H, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x27] = {"DAA", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x27, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x28] = {"JR", 2, {12, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x28, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::Z, 0, false}; // op1 is e8
    standardOpcodes[0x29] = {"ADD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x29, InstructionGroup::X16_ALU, Register::HL, Register::HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x2A] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x2A, InstructionGroup::X8_LSM, Register::A, Register::MEM_HLI, ConditionType::NONE, 0, false};
    standardOpcodes[0x2B] = {"DEC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x2B, InstructionGroup::X16_ALU, Register::HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x2C] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x2C, InstructionGroup::X8_ALU, Register::L, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x2D] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x2D, InstructionGroup::X8_ALU, Register::L, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x2E] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x2E, InstructionGroup::X8_LSM, Register::L, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x2F] = {"CPL", 1, {4}, {FlagModificationType::NONE, FlagModificationType::SET, FlagModificationType::SET, FlagModificationType::NONE}, 0x2F, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x30] = {"JR", 2, {12, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x30, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NC, 0, false}; // op1 is e8
    standardOpcodes[0x31] = {"LD", 3, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x31, InstructionGroup::X16_LSM, Register::SP, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n16
    standardOpcodes[0x32] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x32, InstructionGroup::X8_LSM, Register::MEM_HLD, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x33] = {"INC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x33, InstructionGroup::X16_ALU, Register::SP, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x34] = {"INC", 1, {12}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x34, InstructionGroup::X8_ALU, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x35] = {"DEC", 1, {12}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x35, InstructionGroup::X8_ALU, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x36] = {"LD", 2, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x36, InstructionGroup::X8_LSM, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x37] = {"SCF", 1, {4}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::SET}, 0x37, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x38] = {"JR", 2, {12, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x38, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::C, 0, false}; // op1 is e8
    standardOpcodes[0x39] = {"ADD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x39, InstructionGroup::X16_ALU, Register::HL, Register::SP, ConditionType::NONE, 0, false};
    standardOpcodes[0x3A] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x3A, InstructionGroup::X8_LSM, Register::A, Register::MEM_HLD, ConditionType::NONE, 0, false};
    standardOpcodes[0x3B] = {"DEC", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x3B, InstructionGroup::X16_ALU, Register::SP, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x3C] = {"INC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x3C, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x3D] = {"DEC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x3D, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x3E] = {"LD", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x3E, InstructionGroup::X8_LSM, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0x3F] = {"CCF", 1, {4}, {FlagModificationType::NONE, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3F, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x40] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x40, InstructionGroup::X8_LSM, Register::B, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x41] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x41, InstructionGroup::X8_LSM, Register::B, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x42] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x42, InstructionGroup::X8_LSM, Register::B, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x43] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x43, InstructionGroup::X8_LSM, Register::B, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x44] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x44, InstructionGroup::X8_LSM, Register::B, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x45] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x45, InstructionGroup::X8_LSM, Register::B, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x46] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x46, InstructionGroup::X8_LSM, Register::B, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x47] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x47, InstructionGroup::X8_LSM, Register::B, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x48] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x48, InstructionGroup::X8_LSM, Register::C, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x49] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x49, InstructionGroup::X8_LSM, Register::C, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x4A] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4A, InstructionGroup::X8_LSM, Register::C, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x4B] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4B, InstructionGroup::X8_LSM, Register::C, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x4C] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4C, InstructionGroup::X8_LSM, Register::C, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x4D] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4D, InstructionGroup::X8_LSM, Register::C, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x4E] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4E, InstructionGroup::X8_LSM, Register::C, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x4F] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x4F, InstructionGroup::X8_LSM, Register::C, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x50] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x50, InstructionGroup::X8_LSM, Register::D, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x51] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x51, InstructionGroup::X8_LSM, Register::D, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x52] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x52, InstructionGroup::X8_LSM, Register::D, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x53] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x53, InstructionGroup::X8_LSM, Register::D, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x54] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x54, InstructionGroup::X8_LSM, Register::D, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x55] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x55, InstructionGroup::X8_LSM, Register::D, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x56] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x56, InstructionGroup::X8_LSM, Register::D, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x57] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x57, InstructionGroup::X8_LSM, Register::D, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x58] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x58, InstructionGroup::X8_LSM, Register::E, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x59] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x59, InstructionGroup::X8_LSM, Register::E, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x5A] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5A, InstructionGroup::X8_LSM, Register::E, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x5B] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5B, InstructionGroup::X8_LSM, Register::E, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x5C] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5C, InstructionGroup::X8_LSM, Register::E, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x5D] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5D, InstructionGroup::X8_LSM, Register::E, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x5E] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5E, InstructionGroup::X8_LSM, Register::E, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x5F] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x5F, InstructionGroup::X8_LSM, Register::E, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x60] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x60, InstructionGroup::X8_LSM, Register::H, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x61] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x61, InstructionGroup::X8_LSM, Register::H, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x62] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x62, InstructionGroup::X8_LSM, Register::H, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x63] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x63, InstructionGroup::X8_LSM, Register::H, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x64] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x64, InstructionGroup::X8_LSM, Register::H, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x65] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x65, InstructionGroup::X8_LSM, Register::H, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x66] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x66, InstructionGroup::X8_LSM, Register::H, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x67] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x67, InstructionGroup::X8_LSM, Register::H, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x68] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x68, InstructionGroup::X8_LSM, Register::L, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x69] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x69, InstructionGroup::X8_LSM, Register::L, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x6A] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6A, InstructionGroup::X8_LSM, Register::L, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x6B] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6B, InstructionGroup::X8_LSM, Register::L, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x6C] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6C, InstructionGroup::X8_LSM, Register::L, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x6D] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6D, InstructionGroup::X8_LSM, Register::L, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x6E] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6E, InstructionGroup::X8_LSM, Register::L, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x6F] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x6F, InstructionGroup::X8_LSM, Register::L, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x70] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x70, InstructionGroup::X8_LSM, Register::MEM_HL, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x71] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x71, InstructionGroup::X8_LSM, Register::MEM_HL, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x72] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x72, InstructionGroup::X8_LSM, Register::MEM_HL, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x73] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x73, InstructionGroup::X8_LSM, Register::MEM_HL, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x74] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x74, InstructionGroup::X8_LSM, Register::MEM_HL, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x75] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x75, InstructionGroup::X8_LSM, Register::MEM_HL, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x76] = {"HALT", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x76, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0x77] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x77, InstructionGroup::X8_LSM, Register::MEM_HL, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x78] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x78, InstructionGroup::X8_LSM, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x79] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x79, InstructionGroup::X8_LSM, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x7A] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7A, InstructionGroup::X8_LSM, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x7B] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7B, InstructionGroup::X8_LSM, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x7C] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7C, InstructionGroup::X8_LSM, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x7D] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7D, InstructionGroup::X8_LSM, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x7E] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7E, InstructionGroup::X8_LSM, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x7F] = {"LD", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0x7F, InstructionGroup::X8_LSM, Register::A, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x80] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x80, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x81] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x81, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x82] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x82, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x83] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x83, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x84] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x84, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x85] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x85, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x86] = {"ADD", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x86, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x87] = {"ADD", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x87, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x88] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x88, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x89] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x89, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x8A] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8A, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x8B] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8B, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x8C] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8C, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x8D] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8D, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x8E] = {"ADC", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8E, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x8F] = {"ADC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x8F, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0x90] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x90, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x91] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x91, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x92] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x92, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x93] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x93, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x94] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x94, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x95] = {"SUB", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x95, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x96] = {"SUB", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x96, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x97] = {"SUB", 1, {4}, {FlagModificationType::SET, FlagModificationType::SET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x97, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false}; // Z is 1, N is 1, H is 0, C is 0
    standardOpcodes[0x98] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x98, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0x99] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x99, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0x9A] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x9A, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0x9B] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x9B, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0x9C] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x9C, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0x9D] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x9D, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0x9E] = {"SBC", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0x9E, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0x9F] = {"SBC", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::NONE}, 0x9F, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false}; // C is -
    standardOpcodes[0xA0] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA0, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0xA1] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA1, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0xA2] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA2, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0xA3] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA3, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0xA4] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA4, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0xA5] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA5, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0xA6] = {"AND", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA6, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0xA7] = {"AND", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xA7, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0xA8] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xA8, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0xA9] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xA9, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0xAA] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAA, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0xAB] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAB, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0xAC] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAC, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0xAD] = {"XOR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAD, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0xAE] = {"XOR", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAE, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0xAF] = {"XOR", 1, {4}, {FlagModificationType::SET, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xAF, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false}; // Z is 1
    standardOpcodes[0xB0] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB0, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0xB1] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB1, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0xB2] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB2, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0xB3] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB3, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0xB4] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB4, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0xB5] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB5, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0xB6] = {"OR", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB6, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0xB7] = {"OR", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xB7, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0xB8] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xB8, InstructionGroup::X8_ALU, Register::A, Register::B, ConditionType::NONE, 0, false};
    standardOpcodes[0xB9] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xB9, InstructionGroup::X8_ALU, Register::A, Register::C, ConditionType::NONE, 0, false};
    standardOpcodes[0xBA] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xBA, InstructionGroup::X8_ALU, Register::A, Register::D, ConditionType::NONE, 0, false};
    standardOpcodes[0xBB] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xBB, InstructionGroup::X8_ALU, Register::A, Register::E, ConditionType::NONE, 0, false};
    standardOpcodes[0xBC] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xBC, InstructionGroup::X8_ALU, Register::A, Register::H, ConditionType::NONE, 0, false};
    standardOpcodes[0xBD] = {"CP", 1, {4}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xBD, InstructionGroup::X8_ALU, Register::A, Register::L, ConditionType::NONE, 0, false};
    standardOpcodes[0xBE] = {"CP", 1, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xBE, InstructionGroup::X8_ALU, Register::A, Register::MEM_HL, ConditionType::NONE, 0, false};
    standardOpcodes[0xBF] = {"CP", 1, {4}, {FlagModificationType::SET, FlagModificationType::SET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xBF, InstructionGroup::X8_ALU, Register::A, Register::A, ConditionType::NONE, 0, false}; // Z=1, N=1, H=0, C=0
    standardOpcodes[0xC0] = {"RET", 1, {20, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC0, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NZ, 0, false};
    standardOpcodes[0xC1] = {"POP", 1, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC1, InstructionGroup::X16_LSM, Register::BC, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xC2] = {"JP", 3, {16, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC2, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NZ, 0, false}; // op1 is a16
    standardOpcodes[0xC3] = {"JP", 3, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC3, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0, false}; // op1 is a16
    standardOpcodes[0xC4] = {"CALL", 3, {24, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC4, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NZ, 0, false}; // op1 is a16
    standardOpcodes[0xC5] = {"PUSH", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC5, InstructionGroup::X16_LSM, Register::BC, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xC6] = {"ADD", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xC6, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xC7] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC7, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x00, false};
    standardOpcodes[0xC8] = {"RET", 1, {20, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC8, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::Z, 0, false};
    standardOpcodes[0xC9] = {"RET", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xC9, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xCA] = {"JP", 3, {16, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xCA, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::Z, 0, false}; // op1 is a16
    standardOpcodes[0xCB] = {"PREFIX", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xCB, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, true}; // Special case: isPrefixed = true
    standardOpcodes[0xCC] = {"CALL", 3, {24, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xCC, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::Z, 0, false}; // op1 is a16
    standardOpcodes[0xCD] = {"CALL", 3, {24}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xCD, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0, false}; // op1 is a16
    standardOpcodes[0xCE] = {"ADC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xCE, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xCF] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xCF, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x08, false};
    standardOpcodes[0xD0] = {"RET", 1, {20, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD0, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NC, 0, false};
    standardOpcodes[0xD1] = {"POP", 1, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD1, InstructionGroup::X16_LSM, Register::DE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xD2] = {"JP", 3, {16, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD2, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NC, 0, false}; // op1 is a16
    standardOpcodes[0xD3] = {"ILLEGAL_D3", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xD3, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xD4] = {"CALL", 3, {24, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD4, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NC, 0, false}; // op1 is a16
    standardOpcodes[0xD5] = {"PUSH", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD5, InstructionGroup::X16_LSM, Register::DE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xD6] = {"SUB", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xD6, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xD7] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD7, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x10, false};
    standardOpcodes[0xD8] = {"RET", 1, {20, 8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD8, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::C, 0, false};
    standardOpcodes[0xD9] = {"RETI", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xD9, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xDA] = {"JP", 3, {16, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xDA, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::C, 0, false}; // op1 is a16
    standardOpcodes[0xDB] = {"ILLEGAL_DB", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xDB, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xDC] = {"CALL", 3, {24, 12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xDC, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::C, 0, false}; // op1 is a16
    standardOpcodes[0xDD] = {"ILLEGAL_DD", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xDD, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xDE] = {"SBC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xDE, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xDF] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xDF, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x18, false};
    standardOpcodes[0xE0] = {"LDH", 2, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE0, InstructionGroup::X8_LSM, Register::MEM_A8, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0xE1] = {"POP", 1, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE1, InstructionGroup::X16_LSM, Register::HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xE2] = {"LDH", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE2, InstructionGroup::X8_LSM, Register::MEM_C, Register::A, ConditionType::NONE, 0, false}; // LDH (C), A
    standardOpcodes[0xE3] = {"ILLEGAL_E3", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xE3, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xE4] = {"ILLEGAL_E4", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xE4, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xE5] = {"PUSH", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE5, InstructionGroup::X16_LSM, Register::HL, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xE6] = {"AND", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::RESET}, 0xE6, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xE7] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE7, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x20, false};
    standardOpcodes[0xE8] = {"ADD", 2, {16}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xE8, InstructionGroup::X16_ALU, Register::SP, Register::NONE, ConditionType::NONE, 0, false}; // op2 is e8
    standardOpcodes[0xE9] = {"JP", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xE9, InstructionGroup::CONTROL_BR, Register::HL, Register::NONE, ConditionType::NONE, 0, false}; // JP HL
    standardOpcodes[0xEA] = {"LD", 3, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xEA, InstructionGroup::X8_LSM, Register::MEM_A16, Register::A, ConditionType::NONE, 0, false};
    standardOpcodes[0xEB] = {"ILLEGAL_EB", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xEB, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xEC] = {"ILLEGAL_EC", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xEC, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xED] = {"ILLEGAL_ED", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xED, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xEE] = {"XOR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xEE, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xEF] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xEF, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x28, false};
    standardOpcodes[0xF0] = {"LDH", 2, {12}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF0, InstructionGroup::X8_LSM, Register::A, Register::MEM_A8, ConditionType::NONE, 0, false};
    standardOpcodes[0xF1] = {"POP", 1, {12}, {FlagModificationType::MODIFIED, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xF1, InstructionGroup::X16_LSM, Register::AF, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xF2] = {"LDH", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF2, InstructionGroup::X8_LSM, Register::A, Register::MEM_C, ConditionType::NONE, 0, false}; // LDH A, (C)
    standardOpcodes[0xF3] = {"DI", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF3, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xF4] = {"ILLEGAL_F4", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xF4, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xF5] = {"PUSH", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF5, InstructionGroup::X16_LSM, Register::AF, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xF6] = {"OR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0xF6, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xF7] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF7, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x30, false};
    standardOpcodes[0xF8] = {"LD", 2, {12}, {FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xF8, InstructionGroup::X16_LSM, Register::HL, Register::SP, ConditionType::NONE, 0, false}; // LD HL, SP+e8 (e8 is immediate)
    standardOpcodes[0xF9] = {"LD", 1, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xF9, InstructionGroup::X16_LSM, Register::SP, Register::HL, ConditionType::NONE, 0, false};
    standardOpcodes[0xFA] = {"LD", 3, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xFA, InstructionGroup::X8_LSM, Register::A, Register::MEM_A16, ConditionType::NONE, 0, false};
    standardOpcodes[0xFB] = {"EI", 1, {4}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xFB, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xFC] = {"ILLEGAL_FC", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xFC, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xFD] = {"ILLEGAL_FD", 1, {4}, {FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE,FlagModificationType::NONE}, 0xFD, InstructionGroup::CONTROL_MISC, Register::NONE, Register::NONE, ConditionType::NONE, 0, false};
    standardOpcodes[0xFE] = {"CP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::SET, FlagModificationType::MODIFIED, FlagModificationType::MODIFIED}, 0xFE, InstructionGroup::X8_ALU, Register::A, Register::NONE, ConditionType::NONE, 0, false}; // op2 is n8
    standardOpcodes[0xFF] = {"RST", 1, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, 0xFF, InstructionGroup::CONTROL_BR, Register::NONE, Register::NONE, ConditionType::NONE, 0x38, false};

    // --- CB-Prefixed Opcodes ---
    // Example for one entry (0x00): RLC B
    cbPrefixedOpcodes[0x00] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x00, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x01] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x01, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x02] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x02, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x03] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x03, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x04] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x04, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x05] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x05, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x06] = {"RLC", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x06, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x07] = {"RLC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x07, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x08] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x08, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x09] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x09, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0A] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0A, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0B] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0B, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0C] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0C, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0D] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0D, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0E] = {"RRC", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0E, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x0F] = {"RRC", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x0F, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x10] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x10, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x11] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x11, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x12] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x12, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x13] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x13, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x14] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x14, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x15] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x15, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x16] = {"RL", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x16, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x17] = {"RL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x17, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x18] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x18, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x19] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x19, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1A] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1A, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1B] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1B, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1C] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1C, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1D] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1D, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1E] = {"RR", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1E, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x1F] = {"RR", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x1F, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x20] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x20, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x21] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x21, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x22] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x22, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x23] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x23, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x24] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x24, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x25] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x25, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x26] = {"SLA", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x26, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x27] = {"SLA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x27, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x28] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x28, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x29] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x29, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2A] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2A, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2B] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2B, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2C] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2C, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2D] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2D, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2E] = {"SRA", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2E, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x2F] = {"SRA", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x2F, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x30] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x30, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x31] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x31, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x32] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x32, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x33] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x33, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x34] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x34, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x35] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x35, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x36] = {"SWAP", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x36, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x37] = {"SWAP", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::RESET}, 0x37, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x38] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x38, InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x39] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x39, InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3A] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3A, InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3B] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3B, InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3C] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3C, InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3D] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3D, InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3E] = {"SRL", 2, {16}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3E, InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, 0, true};
    cbPrefixedOpcodes[0x3F] = {"SRL", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::RESET, FlagModificationType::MODIFIED}, 0x3F, InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, 0, true};

    // BIT opcodes (0x40 - 0x7F)
    for (int bit = 0; bit < 8; ++bit) {
        cbPrefixedOpcodes[0x40 + bit * 8 + 0] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 0), InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 1] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 1), InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 2] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 2), InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 3] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 3), InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 4] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 4), InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 5] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 5), InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 6] = {"BIT", 2, {12}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 6), InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x40 + bit * 8 + 7] = {"BIT", 2, {8}, {FlagModificationType::MODIFIED, FlagModificationType::RESET, FlagModificationType::SET, FlagModificationType::NONE}, static_cast<uint16_t>(0x40 + bit * 8 + 7), InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
    }

    // RES opcodes (0x80 - 0xBF)
    for (int bit = 0; bit < 8; ++bit) {
        cbPrefixedOpcodes[0x80 + bit * 8 + 0] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 0), InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 1] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 1), InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 2] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 2), InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 3] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 3), InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 4] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 4), InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 5] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 5), InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 6] = {"RES", 2, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 6), InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0x80 + bit * 8 + 7] = {"RES", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0x80 + bit * 8 + 7), InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
    }

    // SET opcodes (0xC0 - 0xFF)
    for (int bit = 0; bit < 8; ++bit) {
        cbPrefixedOpcodes[0xC0 + bit * 8 + 0] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 0), InstructionGroup::X8_RSB, Register::B, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 1] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 1), InstructionGroup::X8_RSB, Register::C, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 2] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 2), InstructionGroup::X8_RSB, Register::D, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 3] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 3), InstructionGroup::X8_RSB, Register::E, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 4] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 4), InstructionGroup::X8_RSB, Register::H, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 5] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 5), InstructionGroup::X8_RSB, Register::L, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 6] = {"SET", 2, {16}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 6), InstructionGroup::X8_RSB, Register::MEM_HL, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
        cbPrefixedOpcodes[0xC0 + bit * 8 + 7] = {"SET", 2, {8}, {FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE, FlagModificationType::NONE}, static_cast<uint16_t>(0xC0 + bit * 8 + 7), InstructionGroup::X8_RSB, Register::A, Register::NONE, ConditionType::NONE, static_cast<uint16_t>(bit), true};
    }
}

// GetInstance method for the Singleton pattern
// Ensures thread-safe initialization in C++11 and later
OpcodeTables& OpcodeTables::getInstance() {
    static OpcodeTables instance; // Meyers' Singleton
    return instance;
}

// GetInfo method to retrieve opcode details
const OpcodeInfo& OpcodeTables::getInfo(uint8_t opcode, bool prefixed) const {
    if (prefixed) {
        // Using array::at() provides bounds checking and throws std::out_of_range on failure
        try {
            return cbPrefixedOpcodes.at(opcode);
        } catch (const std::out_of_range& oor) {
             LOG_ERROR("OpcodeTables::getInfo CB-prefixed index out of range: " + std::to_string(opcode));
             return unknownOpcodeInfo; // Return the default info member
        }
    } else {
        try {
            return standardOpcodes.at(opcode);
        } catch (const std::out_of_range& oor) {
             LOG_ERROR("OpcodeTables::getInfo standard index out of range: " + std::to_string(opcode));
             return unknownOpcodeInfo; // Return the default info member
        }
    }
}

} // namespace GB